### ISSUE TITLE
details

### ISSUE THREAD

**Issue by Hoodgail** [andersevenrud/avbbs#1]
can u please give more details in the readme.md?

**Comment by andersevenrud** [comment]
Hm, I'm not really sure what I would add. What do you feel is missing here ?

**Comment by Hoodgail** [comment]
idk 😄 ,
Builds a directory of packages for what?
why is this good,
wait like a bundler? ...

**Comment by Hoodgail** [comment]
never mind i get it now, i misunderstood  when u said `Builds a directory of packages.`

**Comment by andersevenrud** [comment]
Hehe.

> why is this good

At the moment this is more of a proof-on-concept thingy. I just created this very quickly to demonstrate ways to approach this to a friend :)

**Comment by Hoodgail** [comment]
oooh ok 😄

**Comment by Hoodgail** [comment]
> oooh ok 😄

thx :)

**Comment by andersevenrud** [comment]
:+1: 

It's working pretty well though, so I'll probably release this properly when I've added a couple of more features (include some templates and more CLI options)
